<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ArdUi</AssemblyName>
    <Version>1.0.0-pre.11</Version>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ArdUi.cs" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.13" />
    <PackageReference Include="Avalonia.Headless" Version="11.3.13" />
    <PackageReference Include="NSec.Cryptography" Version="25.4.0" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <EmbeddedResource Include="release-public.pem" LogicalName="ArdUi.release-public.pem" />
    <EmbeddedResource Include="THIRD-PARTY-NOTICES.md" LogicalName="ArdUi.THIRD-PARTY-NOTICES.md" />
  </ItemGroup>
</Project>
